server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["https://elasticsearch01:9200","https://elasticsearch02:9200"]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: changeme

elasticsearch.ssl.verificationMode: "none"
